# Generated by Django 5.0.3 on 2024-03-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('correo_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.IntegerField()),
                ('mensaje_contacto', models.TextField()),
                ('tipos_contacto', models.IntegerField(choices=[(0, 'Consulta'), (1, 'Sugerencia'), (2, 'Problemas con tu cuenta')])),
            ],
        ),
    ]
