# Generated by Django 5.0.3 on 2024-03-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Usuario', models.CharField(max_length=50)),
                ('apellido_Usuario', models.CharField(max_length=50)),
                ('rut_Usuario', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
