# Generated by Django 4.2.1 on 2024-03-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_datos_alumnos_telefono_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_alumnos',
            name='telefono_Usuario',
            field=models.IntegerField(default=''),
        ),
    ]
