# Generated by Django 4.2.1 on 2024-03-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_alter_datos_alumnos_telefono_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_alumnos',
            name='carrera_Usuario',
            field=models.IntegerField(choices=[[0, 'Analista Programador Computacional'], [1, 'Contabilidad Tributaria'], [2, 'Administración de Empresas'], [3, 'Desarrollo de Aplicaciones'], [4, 'ingeniería en Desarrollo de Software']], default=0),
        ),
    ]
