# Generated by Django 5.0.3 on 2024-03-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_alter_datos_alumnos_carrera_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_alumnos',
            name='telefono_Usuario',
            field=models.CharField(default='', max_length=20),
        ),
    ]
