# Generated by Django 5.0.3 on 2024-03-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_alter_datos_alumnos_telefono_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_alumnos',
            name='carrera_Usuario',
        ),
    ]
