# Generated by Django 5.0.3 on 2024-03-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0010_datos_alumnos_carrera_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_alumnos',
            name='semestre_Usuario',
            field=models.CharField(default='', max_length=12),
        ),
    ]
