# Generated by Django 5.0.3 on 2024-03-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_alter_datos_alumnos_carrera_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_alumnos',
            name='carrera_Usuario',
            field=models.IntegerField(choices=[(0, 'Analista Programador Computacional'), (1, 'Contabilidad Tributaria'), (2, 'Administración de Empresas'), (3, 'Desarrollo de Aplicaciones'), (4, 'ingeniería en Desarrollo de Software')], default=''),
        ),
        migrations.AlterField(
            model_name='datos_alumnos',
            name='telefono_Usuario',
            field=models.CharField(default='+569 ', max_length=20),
        ),
    ]
