# Generated by Django 5.0.3 on 2024-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_alter_datos_alumnos_carrera_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_alumnos',
            name='confirmar_password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
