# Generated by Django 5.0.3 on 2024-04-23 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0015_datos_moderador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_moderador',
            name='grupo',
        ),
    ]
