# Generated by Django 5.0.3 on 2024-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0016_remove_datos_moderador_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_post', models.CharField(max_length=50)),
                ('descripcion_Post', models.TextField(max_length=200)),
                ('imagen_post', models.ImageField(null=True, upload_to='postAlumno')),
            ],
        ),
    ]
