# Generated by Django 5.0.3 on 2024-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0021_alter_postalumnos_tipo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalumnos',
            name='tipo_post',
            field=models.CharField(choices=[(1, 'Grupo Estudio'), (2, 'Grupo Equipo'), (3, 'Grupo Ocio')], max_length=50),
        ),
    ]
