# Generated by Django 5.0.3 on 2024-05-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0023_alter_postalumnos_tipo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono_contacto',
            field=models.CharField(default='+569 ', max_length=20),
        ),
    ]
