# Generated by Django 5.0.3 on 2024-05-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0024_alter_contacto_telefono_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono_contacto',
            field=models.CharField(max_length=20),
        ),
    ]
