# Generated by Django 5.0.3 on 2024-05-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0028_alter_datos_alumnos_carrera_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipos_contacto',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Sugerencia', 'Sugerencia'), ('Problemas con tu cuenta', 'Problemas con tu cuenta')], default='', max_length=100),
        ),
    ]
